apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - github.com/pittar-demos/demo-catalog/openshift-gitops-instances/argocd/openshift-gitops?ref=main
