kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-gitops

resources:
  - tenants-project.yaml
  - ../../../04-tenants/superhero-battle/cicd
  - ../../../04-tenants/superhero-battle/dev
  - ../../../04-tenants/superhero-battle/test